# Generated by Django 5.0.4 on 2024-05-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_movie_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='title',
        ),
    ]
