# Generated by Django 5.0.4 on 2024-05-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_movierev_delete_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierev',
            name='movie_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
